Repository Discord-Resources-Wiki/Discord-Resources-Wiki, pull requests merged in 2021-11, with the labels that each got.

#13 Big changes
  Wiki_Files/Resources.md
  Wiki_Files/_Sidebar.md
Labels: New Resource, Adjustment

#15 Added a new resource
  Wiki_Files/Resources.md
Labels: New Resource

#17 Added a section about running the wiki at home
  wiki/about.md
Labels: enhancement

#27 Add markdown remark plugins for line breaks, user widgets, and invite widgets
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/OutsideClickHandler.jsx
  src/components/Tooltip.jsx
  src/components/UserWidgetInline.jsx
  src/css/Tooltip.module.css
  src/css/UserWidgetInline.module.css
  src/css/custom.css
  src/plugins/inviteWidgetPlugin.js
  src/plugins/linebreakPlugin.js
  src/plugins/userWidgetInlinePlugin.js
  wiki/resources/bots/best.md
  wiki/resources/bots/info.md
  wiki/resources/moderation.md
  wiki/resources/official-servers.md
  wiki/resources/tools/converters.md
  wiki/resources/tools/discord.md
  wiki/resources/tools/other.md
  wiki/resources/tools/phishing.md
  wiki/resources/unofficial-resources.md
  wiki/resources/unofficial-servers.md
Labels: enhancement

#36 ⚒️ Header Fix
  wiki/resources/tools/discord.md
  wiki/resources/tools/programming.md
Labels: Adjustment

#66 Replace & Add 2 Items
  wiki/resources/tools/converters.md
Labels: New Resource, Adjustment

#64 Fix grammar, clarification, and formatting
  wiki/resources/basics.md
  wiki/resources/bots/best.md
  wiki/resources/bots/info.md
  wiki/resources/moderation.md
  wiki/resources/official-links.md
  wiki/resources/official-servers.md
  wiki/resources/tools/converters.md
  wiki/resources/tools/discord.md
  wiki/resources/tools/other.md
  wiki/resources/tools/phishing.md
  wiki/resources/tools/programming.md
  wiki/resources/unofficial-resources.md
  wiki/resources/unofficial-servers.md
Labels: Adjustment
